### ISSUE TITLE
Update min version to 10.0.7

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/password_policy#11]
Before new release with (password_history) #10, we should update min version to 10.0.7.

**Comment by DeepDiver1975** [comment]
needs to be taken care of when doing the next release ...

**Comment by patrickjahns** [comment]
@DeepDiver1975 @karakayasemi 
Will it be 10.0.7 or 10.0.8?

**Comment by karakayasemi** [comment]
https://github.com/owncloud/password_policy/pull/10#issuecomment-363726713 , due to the hotfix, it will be 10.0.8

**Comment by karakayasemi** [comment]
We can close this. Min version will be 10.0.9. see #17
