### ISSUE TITLE
Add acceptance tests on Oracle to the drone matrix

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#146]
PR #101 introduced Oracle-specific code. So it would be good to run the acceptance tests against Oracle. PR #145 has demonstrated that they will pass.

May  as well add pgsql to the matrix while it is being touched.

**Comment by DeepDiver1975** [comment]
requires https://github.com/owncloud/testing/pull/27

**Comment by phil-davis** [comment]
Testing PR https://github.com/owncloud/testing/pull/27 has been merged. We can move forward with this issue.

**Comment by phil-davis** [comment]
Done in #152
