### ISSUE TITLE
Add or refactor occ command acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#155]
Review how the current acceptance tests use and test the various password policy ``occ`` commands.

Make a ``cli`` acceptance test suite and put relevant tests in it.

Main QA issue: https://github.com/owncloud/QA/issues/570

**Comment by skshetry** [comment]
The tests for the `cli` was already there, sharing same suite with the `api`. I have separate those into separate suites. See #162 PR

**Comment by phil-davis** [comment]
Done
