### ISSUE TITLE
Password set after first login (Create User with username and mail)

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/password_policy#158]
After creating a user with a username and an email address. Owncloud sent me an email with a link to set a password. After setting this password, I log in for the first time and have to set a new password again.

**Comment by PVince81** [comment]
What settings did you set ? I guess you set the "force setting password on first login" option ?

**Comment by PVince81** [comment]
A possible fix, I guess, is to make sure that whatever flag is being set after a password is set also gets set by the guests app. I'd expect that whatever API call sets the password sets such password.

**Comment by prsnbrg** [comment]
Yes I have set the setting „Force setting password on First Login“.

Fine, but this is a core update, right?

**Comment by PVince81** [comment]
Not necessarily. I don't remember the details from the code. We might also need to check if said flag exists and when the password policy is reading it. Maybe it reads it too early and does not get the update that the guest app would trigger. Needs some research.

**Comment by PVince81** [comment]
should be fixed in the next app release through https://github.com/owncloud/password_policy/pull/171
