### ISSUE TITLE
Add tests for new user creation flow

### ISSUE THREAD

**Issue by PVince81** [owncloud/password_policy#160]
@phil-davis @individual-it FYI

**Comment by paurakhsharma** [comment]
only acceptance tests relating to https://github.com/owncloud/enterprise/issues/2970 are made on PR  https://github.com/owncloud/password_policy/pull/161. Other required tests for this issues are yet to be made.

**Comment by paurakhsharma** [comment]
PR #161 should solve it. This PR will only pass after https://github.com/owncloud/core/pull/33453 is merged.
