### ISSUE TITLE
[For 10.1] Password policy 2.0.2

### ISSUE THREAD

**Issue by PVince81** [owncloud/password_policy#176]
### Reason
- Set max version to 10 for Semver
- First login enforcement fixes https://github.com/owncloud/password_policy/pull/171
- LDAP login enforcement fixes https://github.com/owncloud/password_policy/pull/173

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "2.0.2 Testplan" https://github.com/owncloud/password_policy/issues/179
- [x]  Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) 

### Documentation
- [x] Changes in the docs needed? => hmm, no

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/password_policy/pull/177
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/password_policy/pull/177
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/7b8Yx2iU42bkTDX
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist` => https://cloud.owncloud.com/index.php/s/mJL3bGDvBqdFzhL
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/password_policy/pull/182

**Comment by PVince81** [comment]
@DeepDiver1975 please upload to marketplace: https://cloud.owncloud.com/index.php/s/mJL3bGDvBqdFzhL

changelog here: https://github.com/owncloud/password_policy/blob/release-2.0.2/CHANGELOG.md#202

**Comment by DeepDiver1975** [comment]
released
