### ISSUE TITLE
acceptance tests fail after 30 minutes with integrity check messages

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#186]
See PR #184 
After 30 minutes and integrity check seems to "go off". After that, there is an extra notification in the webUI for the administrator - ``There were problems with the code integrity check`` - This started happening last Friday night.

There happen to be acceptance tests that are checking for notifications about the password not meeting the policy. These fail because of the extra notification that starts happening 30 minutes into the test run.

Note: the fail in PR #184 is only in PHP 5.6 - because that runs slow. PHP 7.* runs faster and finishes in less than 30 minutes.

PR #185 makes the test scenarios go longer than 30 minutes. It demonstrates that the problem happens just the same for all PHP versions.

We can easily adjust the tests to ignore other "bonuses" in the notifications.

But why do we seem to now be getting "integrity check" errors?
Is it an integrity check problem in the password policy code, or the core stable10 QA tarball?

@PVince81 @individual-it

**Comment by PVince81** [comment]
is this still happening ?

**Comment by phil-davis** [comment]
Yes, when the drone agent is a bit slow and a suite runs for >30 minutes then this problem is evident.

I wish I had an idea why this happens.

PR #208 tries it again.

**Comment by phil-davis** [comment]
Not seen in a test CI run this morning. See comment https://github.com/owncloud/password_policy/pull/208#issuecomment-469530805

Closing this issue.We can always open again if the problem appears again.

**Comment by individual-it** [comment]
An other level of the issue is that the app itself is cloned from git and not signed. see https://github.com/owncloud/QA/issues/614
