### ISSUE TITLE
Cannot use extra non-alphanumeric characters when special characters are defined

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#19]
1. In Admin, settings, security, set the counts to 8 characters, 1 lowercase, 1 uppercase, 1 number, 1  special character
2. Enable "Define special characters" and specify some special characters, e.g. ``#!$&`` and Save
3. Login as some user, go to settings, security and try to change your password to ``Test1234#*``
Error message is displayed:
```
The password contains invalid special characters. Only #!$& are allowed.
```

But you have specified "at least 1 of the defined special characters". So, in my mind, you have met the requirement.

You have also exceeded the requirement by using other characters that are not in the subsets "lower", "upper", "numbers" or "special". But that is  "a good thing".

As a sysadmin, I would expect this to be allowed.

**Comment by PVince81** [comment]
this is expected because you cannot use "*" which wasn't defined.

Closing and added comment here to improve the label: https://github.com/owncloud/password_policy/issues/72#issuecomment-406609599
