### ISSUE TITLE
Password expiry

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/password_policy#2]
Expectation:
- User passwords expire after X days
- User should be notified Y days before the password expires to change the password
- User should be notified when the password has expired

To be clarified:
- where to implement the password change dialog
  - [ ] core
  - [ ] this app

**Comment by karakayasemi** [comment]
I've been working on the subject a little bit. In the user.afterlogin event we can check for expiry and send notification or e-mail to notify user x days before. However, I could not find any way to redirect a user to password change page from the app. I have two ideas to overcome this situation:
1. We can send an exception which gives the link to the password change page. Password change template can be stored in the app, in this way, theoretically, we don't need any change in the core. But, the user needs to click a button to go to password change page.
2. We can implement something similar with two-factor structure in the core, but it sounds a bit dirty and makes login structure even more complicated.

Shortly, the question is how can I redirect a user to password change page from an app? I'm not sure about my ideas. I would appreciate any help. Thanks.

**Comment by DeepDiver1975** [comment]
My guts feeling is telling me the password change page should be part of core.
Summoning @PVince81 @butonic @tomneedham for more input ....

**Comment by PVince81** [comment]
Ideally we should reuse and enhance the password change page from core.

Currently I think that page is the "password forgotten" page that is triggered by a "password forgotten" token routed there. Maybe a quick look at the guests app might help find out how, and see what link is sent in the email and how it is generated. I suspect that to reuse the current mechanism the password_policy app would also need to automatically generate this "password forgotten" token once before redirecting.

**Comment by PVince81** [comment]
This was now implemented as an account module in the password policy app.

Remaining work for notifying about expiration was raised here: https://github.com/owncloud/password_policy/issues/18
