### ISSUE TITLE
Existing webUI session continues to work after password expires

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#22]
Note: When testing this stuff, I have changed my local code so it thinks the password expiry setting is in seconds, not days. So I can just wait 90 seconds rather than 90 days to see the effect!

In real life, the scenario will be:

1) The user is logged in on the webUI (or any other method of access that has cookies/tokens etc by which the server "believes/endures" the session) at 23:59:59 on the day the password should expire.
2) The user is able to keep working in the webUI into the next day. And for as long as the cookie/token/whatever keeps being honored by the server.
3) The user logs out.
4) The user logs  in again, they get the "Password change required" page - good

Question: Is the behavior at step (2) OK? Or is there a requirement to log the user out/take them to the "password change required" as soon as they do something in the webUI after the expiry time?

**Comment by PVince81** [comment]
Good find. I asked @pmaier1 and @butonic and this is by design for now.

Let's keep the ticket as we should document this.

**Comment by butonic** [comment]
@phil-davis actually the session will check the password every 5 min ... so 5 min after the password expired the web session should be unusable. See https://github.com/owncloud/core/blob/0bdf7031e271cf1ba587cd0125d831b603e1fafb/lib/private/User/Session.php#L745

**Comment by phil-davis** [comment]
OK - I can verify that easily. I will report back...

**Comment by phil-davis** [comment]
I think this can be closed - a 5 minute delay after midnight to force password change should be acceptable?

**Comment by butonic** [comment]
yup
