### ISSUE TITLE
"Create public link" - unclear behavior

### ISSUE THREAD

**Issue by kazh000** [owncloud/password_policy#220]
Owncloud ver 10.1.1-1+1.1
installed as debian package
Application "Password policy" ver 2.0.2

Issue: I create public link - "Sharing" -> "Public links" -> "Create public link". I enter a weak password in field "Password" and fill out other fields. I press button "Share" and all fields become grey but there is no any notification. So users of the owncloud cannot understand what is happening and what to do. I haven't found in the documentation proper behavior of the "Password policy" in such situation. And I haven't seen any error message in log file "data/owncloud.log". Could you explain the notification should appear or not. If the behavior of my instance of owncloud is wrong how I can get error message.

**Comment by PVince81** [comment]
sounds like a bug

**Comment by kazh000** [comment]
Is there possibility to get more debug information?

**Comment by PVince81** [comment]
@kazh000 check the network console of the browser and see if there is an error response with a status message. I suspect that the bug might be that the status message does arrive but doesn't get displayed for some reason.

Also check the browser JS console for errors

**Comment by phil-davis** [comment]
I tested on `stable10` branch and it gives me a message:
![Screenshot_2019-04-30 Files - ownCloud](https://user-images.githubusercontent.com/1535615/56965264-9287c980-6b7c-11e9-8ca4-e0b0d251f06d.png)

This kind of stuff is tested in CI, e.g. https://github.com/owncloud/password_policy/blob/master/tests/acceptance/features/webUIPublicShareLink/publicShareLinkLowercaseLetters.feature#L27

I wonder what is special about your system?

**Comment by kazh000** [comment]
uname -a: inux name 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1 (2019-04-12) x86_64 GNU/Linux
dpkg -l owncloud-files: owncloud-files                        10.1.1-1+1.1

I have got JS error:
sharedialoglinkshare…bdf2223e21a9d8a:213 Uncaught TypeError: Cannot read property 'ocs' of undefined
    at error (sharedialoglinkshare…bdf2223e21a9d8a:213)
    at options.error (backbone.js?v=2dc0d5…df2223e21a9d8a:1887)
    at Object.options.error (backbone.js?v=2dc0d5…df2223e21a9d8a:1407)
    at j (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at x (jquery.js:8266)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)

**Comment by kazh000** [comment]
I have found an error message in the nginx log: "POST /ocs/v2.php/apps/files_sharing/api/v1/shares?format=json HTTP/2.0" 403

**Comment by PVince81** [comment]
you could try with 10.2.0 RC1 then in case this was already fixed: https://central.owncloud.org/t/owncloud-server-10-2-0-rc1-released/19499/2

did you test stable10 on the same server and setup ?

**Comment by kazh000** [comment]
Now I use debian package. I'll make a copy of VM and try to install from src. I'll send a result.

**Comment by kazh000** [comment]
Unfortunately I have to postpone it until next week

**Comment by kazh000** [comment]
Now version is 10.2.0-1+1.1 but the issue exists.

**Comment by kazh000** [comment]
I have replace nginx by apache2 and it fixes the issue. So the plugin "Password Policy" is incompatible with nginx :(.
