### ISSUE TITLE
[User Creation] Password Policy 2.1.0

### ISSUE THREAD

**Issue by micbar** [owncloud/password_policy#236]
**REMINDER:** Please add your name to the checkbox when you have completed an item

### Reason

- Release needed for https://github.com/owncloud/core/issues/35743

### QA

- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "2.1.0 Testplan" @davitol https://github.com/owncloud/password_policy/issues/269

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping @owncloud/marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => https://github.com/owncloud/password_policy/releases/tag/v2.1.0RC1

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number

**Comment by micbar** [comment]
@davitol Just created https://github.com/owncloud/password_policy/releases/tag/v2.1.0RC1

**Comment by davitol** [comment]
@micbar Password Policy tarball 2.1.0RC1 was tested and works fine

To be considered:

https://github.com/owncloud/password_policy/pull/270


and delete from the changelog the items said to be deleted in https://github.com/owncloud/password_policy/issues/269#issuecomment-562015874

**Comment by micbar** [comment]
@davitol I created the Final https://github.com/owncloud/password_policy/releases/tag/v2.1.0

But I always want to inform Users about changes in the PHP Support.
Thanks for the other changes in the Changelog, I adapted it and included the new doc link PR from you.

**Comment by micbar** [comment]
Please test and @davitol @HanaGemela give me a final QA-ready mark.

**Comment by davitol** [comment]
> Please test and @davitol @HanaGemela give me a final QA-ready mark.

Sanity tested with MacOS Desktop Client 2.5.4 and 2.6.0 and everything went fine. QA- ready from my POV (@HanaGemela @micbar )
