### ISSUE TITLE
Password expiry for accounts that exist prior to the app being enabled

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#24]
Steps to reproduce

1. As admin, add a user account ``user123``
2. Login as ``user123`` and make sure things are "normal for you"
3. As admin, install and enable the ``password_policy`` app
4. Set a user password policy of ``xx`` days until user password expires
5. Wait ``xx`` days
6. Login as ``user123``

Expected behavior:
- the user is taken to the password change page

Actual behavior:
- the password continues to work

**Comment by phil-davis** [comment]
To test this, I use my branch in PR #23 which shortens the password expiry to be in seconds, not days.
That works fine for me in ordinary testing.

**Comment by phil-davis** [comment]
What is the requirement?

I suppose there is no record of data of last password change for existing accounts, so there is no way to accurately measure their password expiry for enforcing the first change.

Perhaps if there is no previous password change record for a user, then either:
1) trigger forced password change
or
2) when password_policy is enabled, remember somewhere the date it is enabled. Use that as the "default last password change" date. So existing users will get a password change triggered typically 90 days after the app was enabled.

Option (1) will trigger an immediate mass of forced password changes, resulting in a surge of help desk calls on the first day.

Option (2) will trigger the same surge towards the 90 day point.

**Comment by PVince81** [comment]
@pmaier1 please clarify requirement.

I'd consider this a release blocker for the expiry as it would not work for existing users and will likely be reported as "broken"

**Comment by pmaier1** [comment]
This boils down to: Password expiration policies only apply to users added after password_policy has been enabled? This would clearly be a release blocker. Expiration needs to apply to all (local) users no matter if they were created before or after activating the policy. Not sure how the point in time that starts the expiration period is defined. I would be ok with starting the period when the app is enabled, I think.

**Comment by PVince81** [comment]
The point in time is based on the last record of whenever a user last changed their password.
Such record did not exist, so we need to decide.

As discussed in a chat, let's use the "date when the policy got activated" for every user where no record exists.

This is solution 2 as proposed by @phil-davis 

Since the app wasn't released yet, we can assume that no one has enabled the new policy yet in the real world so no migration is needed.

Estimate: 0.5md

**Comment by pmaier1** [comment]
> As discussed in a chat, let's use the "date when the policy got activated" for every user where no record exists.

Sounds good from my POV. As this diverges from the original concept/implementation, @butonic please confirm.

**Comment by butonic** [comment]
The idea is to use the occ command to force a password change on the next login or at a given expiry date. When you enable password policy the admin has to manually think about existing users. We can document a bash script to iterate over all users and set an expiry date. What is supposed to happen when he app is disabled and then enabled again? Should that reset the password expiry for all users? No. Is password policy disabled during upgrades?

**Comment by phil-davis** [comment]
Yes, then the admin can force password change to subsets of users each day/week... if they wish, to get the policy implemented in a staggered way.

Does the ``occ`` command exist yet?

**Comment by PVince81** [comment]
Now thinking of the roles concept, we usually say that the sysadmin who has access to occ is not always the same as the ownCloud admin who has no access to occ.

For user management I'd expect the ownCloud admin to be the one who sets the password policies.
This means such role might not have occ access to make the above adjustment.

@butonic @pmaier1

**Comment by PVince81** [comment]
> Does the occ command exist yet?

Yes, it only lets you expire or set expiration date for a single user

**Comment by butonic** [comment]
if a password change by the admin does not add e hastory entry that is a bug

**Comment by butonic** [comment]
occ command is here https://github.com/owncloud/password_policy/pull/15/files#diff-6a4c4c90288e82e7bd30734c41d164a8R33
supports single user password expiry by date. can be scripted to set a date for all users ...

**Comment by PVince81** [comment]
Ok, we agreed with @butonic to go with the current occ command then.

In later releases we can provide an `--all` switch and `--group` switch to apply an expiry date to multiple users at once.

@phil-davis can you retest the scenario by using the occ command with the test users to confirm it works ?

**Comment by PVince81** [comment]
Also need to verify that command does not create entries when applied to LDAP users because that could make them be stuck in expired mode.

**Comment by PVince81** [comment]
@pmaier1 can you confirm that the "occ" command part is acceptable ? see https://github.com/owncloud/password_policy/issues/24#issuecomment-403509269

basically an admin needs to run occ for users who existed before the password policy app was enabled. the command will trigger expiry for said users with a given date.

**Comment by pmaier1** [comment]
> For user management I'd expect the ownCloud admin to be the one who sets the password policies.
This means such role might not have occ access to make the above adjustment.

This is a very good point. I agree that the expectation here is that it's the ownCloud admin via web interface who imposes the policies. But this is just about existing users, right? In a fresh installation scenario, what is necessary to be done by the system administrator? If it's either nothing or running an oC command / setting up a cronjob once, I'm fine with it.

**Comment by pmaier1** [comment]
Just talked to @PVince81. Approach is acceptable for v1. THX

**Comment by PVince81** [comment]
For the next version I suggest adding `--all` and `--group` to make it more convenient (less painful)

**Comment by phil-davis** [comment]
Issue #39 raised for adding ``--all`` and ``--group`` options.

**Comment by PVince81** [comment]
Closing in favor of documentation ticket: https://github.com/owncloud/documentation/issues/4273

@pmaier1 should we also add something to the release notes ? well, we don't have release notes for apps yet it seems.

**Comment by PVince81** [comment]
After trying to formulate how this works in the above doc ticket, I realized that this is way to complex as an admin I don't want to have to understand that many details.

We'll use this solution for the first version to save time.

We should continue exploring the possibilities to remove this needed step, or at least reduce the number of states a user password can be in (see https://github.com/owncloud/documentation/issues/4273#issuecomment-404781211)

I'm reopening this ticket.

@phil-davis please post your extended ideas

**Comment by phil-davis** [comment]
We could record a date-time-stamp of when the password policy app is activated. Then when a user is logging in, do the normal algorithm that gets the date-time-stamp of their last password change from the history. Only if they have no last password change, then we get the password policy activation date-time-stamp, and write a dummy password change history entry for the user, with that date-time-stamp. The 2nd query only ever happens once for users that do not yet have a password history entry - so will become a performance non-issue after the app has been enabled for a while. And it gradually fills in history entries for each user (rather than having some big job on app activation)

That would provide a default "fallback" to start off user's password history - passwords will end up reaching the first expiration "90" days after the app is enabled. 

The admin could still use the occ command to set explicit password expiry dates if they like. (Which they can always do any time)

**Comment by PVince81** [comment]
in the end we settled on the occ command
