### ISSUE TITLE
Enable password_policy guests tests with core tarball when 10.3 is available

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#245]
guests app release https://github.com/owncloud/guests/releases/tag/v0.8.2 requires core 10.3

Some password_policy drone CI test matrix entries were disable in PR #244 because the guests app cannot be enabled on core 10.2.1

Enable those again when a core release candidate... tarball is available for 10.3

**Comment by PVince81** [comment]
can we close or should this be redone for RC ?

**Comment by phil-davis** [comment]
Closing this, it is done for 10.3.0alpha.
We have to refactor the test matrix for all apps with acceptance tests as 10.3.0 comes towards release, but that is a separate/bigger task.
