### ISSUE TITLE
When "force change on first login" is not set, user password never expires

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#25]
Steps to reproduce

1. As admin, install and enable the ``password_policy`` app
2. Set a user password policy of ``xx`` days until user password expires
3. Do not set "force change on first login"
4. As admin, add a user account ``user123``
5. Login as ``user123`` and make sure things are "normal for you". You are not asked to change your password.
6. Wait ``xx`` days
7. Login as ``user123``

Expected behavior:
- the user is taken to the password change page

Actual behavior:
- the password continues to work

**Comment by phil-davis** [comment]
To test this, I use my branch in PR #23 which shortens the password expiry to be in seconds, not days.
That works fine for me in ordinary testing.

**Comment by phil-davis** [comment]
I suspect that this also has another somewhat less annoying side effect:
1) Policy is to change passwords every 90 days
2) Have a user that changed their password 80 days ago
3) The user is in a mess, forgotten their password and somehow cannot reset their own password. They sit with the sysadmin/helpdesk who changes their password from an admin account
4) 10 days later they get forced to change their password (because the password change by admin is not remembered as a user password change)

**Comment by PVince81** [comment]
Estimate: 0.5md

Proposed technical solution:

- Detect password change through user creation and password change hooks, and store the timestamp in the database.

**Comment by pmaier1** [comment]
Yep, release blocker.

From https://github.com/owncloud/password_policy/issues/24#issuecomment-403464859

> As discussed in a chat, let's use the "date when the policy got activated" for every user where no record exists.

You would then have a point in time. But for a policy that was activated two years ago, this would mean every new user would need to change their password on first login, though. That's tricky. 

> Proposed technical solution:
Detect password change through user creation and password change hooks, and store the timestamp in the database.

Yep, so for every new user (and when pw changed by admin) there will be a record. I like the idea. @butonic please confirm/comment.

**Comment by butonic** [comment]
If the idea is to store the timestamp in the old passwords table, then +1

**Comment by phil-davis** [comment]
I agree, populating ``user_password_history`` with the initial password that the admin gives seems quite reasonable, and will ensure all new users get off to a good start.

**Comment by butonic** [comment]
if a password change by the admin does not add a history entry that is a bug

**Comment by sharidas** [comment]
Below are my observations in the environment master branches of core + password_policy
- Create `admin` user and enable password_policy app.
- Apply https://github.com/owncloud/password_policy/pull/23 on top of the master branch of password_policy
- Enable password expires under `User password policies` with value 25 seconds.
- Now as `admin` user create `user1` with password `1`
- Try to login as `user1` and logout.
- Verified that table `oc_user_password_history` entry is created for the same.
- Update the password of `user1` to `123`.
- Again login to  user `user1` and logout immediately
- After sometime ( after say 1 minute or more ) try to login as `user1`
- The page is redirected to change the password for `user1`.

Below are the details logged in the `oc_user_password_history` table:
```
sqlite> select * from oc_user_password_history;
id          uid         password                                                        change_time
----------  ----------  --------------------------------------------------------------  -----------
1           user1       1|$2y$10$O3kDFZJGJcYuIt2lVarEo.mDs8DYobRDMpkjK0F4X1OYx/EWYg5Uy  1531151276 
2           user1       1|$2y$10$8r7HAtk4M7Y28R7gmRY5Ue41S27ksOs3BYJ4BdAdhgoND..zNJTmq  1531205211 
3           user1       1|$2y$10$tXkbUNC/mHtWIhWkwp0meuNYLHTRTWIr1i1EIDWyatt/fJriDdoTm  1531205712 
sqlite>
```

**Comment by phil-davis** [comment]
@sharidas at step:
- Verified that table oc_user_password_history entry is created for the same.
I do not see any ``oc_user_password_history``
I tried with both core ``master`` and ``stable10``
So I am not sure why you cannot reproduce this issue.

**Comment by sharidas** [comment]
I got the issue why I was able to get the table populated in https://github.com/owncloud/password_policy/issues/25#issuecomment-403723582
If the `admin` user tries to update the password, the user_password_history table is populated. Which means @jvillafanez patch is the right one. That is listen to the event when user is created.

**Comment by sharidas** [comment]
https://github.com/owncloud/password_policy/pull/34 PR does fix the issue. When the user is created, the `user_password_history` table gets populated:
```
sqlite> select * from oc_user_password_history;
id          uid         password                                                        change_time
----------  ----------  --------------------------------------------------------------  -----------
1           user1       1|$2y$10$0CWiu0wzJu.DoPUanySms.EMyYnhAdFU5O8SGtjJGNzc0.pSmhxpa  1531211725 
sqlite> 
```
