### ISSUE TITLE
Special character list can be empty when "Define special characters" is checked

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#26]
Steps to reproduce

1. As admin, install and enable the ``password_policy`` app
2. Enable 1 "special characters"
3. Do not set "force change on first login"
4. Enable "Define special characters"
5. Blank out the list of special characters
6. Save
7. Login as some user, attempt to change your password

Actual behavior:
- you are forced to use a special character in your password
- you can use any special character

Expected behavior:
Who knows?

**Comment by phil-davis** [comment]
Nothing is "broken" here. It just looks odd on the admin settings UI.

If you leave the defined special characters list empty, then setting the "define special characters" checkbox makes no difference to the behavior of the app.

Perhaps:
1) If "define special characters" is checked, then the UI should enforce the special characters list to be non-empty.
or
2) There is not really an issue here, close this issue.

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/password_policy/issues/41#issue-340602479
