### ISSUE TITLE
Previous passwords are remembered after user is deleted

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#28]
Steps to reproduce:
1. Have password_policy enabled with "different than last passwords" checked and some number of "last passwords" specified (e.g. 3).
2. As an admin, create user ```test1`` with password ``Test1111##``
3. Login to ```test1``, change your password to ``Test1234##`` and logout.
4. As an admin, delete ``test1``
5. As an admin, create user ```test1`` with password ``Test1111##`` or ``Test1234##``

The admin is told that the password must be different to the last 3 passwords.

**Comment by phil-davis** [comment]
I noticed this because I saw that:
```
mysql> select * from oc_user_password_history;
```
was growing with a list of password hashes for users that I had deleted.

When a user is deleted, should password_policy be listening to a  hook from that, and delete the password history also?

If so, then what should happen when password_policy is disabled. Users will be deleted but their password history left behind in ``oc_user_password_history``

**Comment by phil-davis** [comment]
I think this is low priority. It will not hurt anybody who happens to re-use a ``uid`` and happens to try to re-use a previous password - whether or not the real user is the same person. They can just choose another password. So it could be fixed whenever the needed hook(s) appear in core.

I raised the issue more because it is nice to keep databases tidy and not have old "unlinked" data hanging around.

**Comment by PVince81** [comment]
similar to https://github.com/owncloud/password_policy/issues/53

I think both together should be around 0.5md

**Comment by PVince81** [comment]
put it together in a single ticket https://github.com/owncloud/password_policy/issues/69
