### ISSUE TITLE
Attempts to change LDAP user passwords give password policy messages

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#29]
Steps to reproduce:
1. setup LDAP on your system - e.g. https://github.com/owncloud/core/wiki/How-to-test-user_ldap
2. as an admin, on the webUI, attempt to change the password of an LDAP user
- you get messages about the password being too short...
- when you enter a password that meets the policy, then you get ``Unable to change password`` 

3. from the command line, attempt to reset the password of an LDAP user:
```
./occ user:resetpassword zombie5
Enter a new password: 
Confirm the new password: 

In Length.php line 33:
                                                                  
  The password is too short. At least 8 characters are required.  
                                                                  

user:resetpassword [--password-from-env] [--] <user>
```

If you enter a password that meets the policy, then you get:
```
./occ user:resetpassword zombie5
Enter a new password: 
Confirm the new password: 
Error while resetting password!
```

The password policy hooks are "getting in first" and misleading you into thinking that maybe you can have success if you meet the policy requirements in the message.

Nothing is broken, but it would be a nicer user experience if:

1) ``password_policy`` hooks do not get invoked for non-local users (or their code understands and does nothing, or they are invoked after the code that emits ``Unable to change password`` so that actually that error message gets emitted first or...)

2) Messages like ``Unable to change password`` and ``Error while resetting password!`` gave a better clue about why - that the password is managed by some other back-end authentication system.

Item 2 is not the responsibility of ``password_policy``, I am just mentioning it here while I think of it.

**Comment by PVince81** [comment]
from my understand you shouldn't even be able to change the password at all from OC for LDAP users, so we should remove the field from the UI.

for the CLI part, would need to detect that changing password is not supported for that user's backend and abort directly with an error message

**Comment by phil-davis** [comment]
> so we should remove the field from the UI

Which will be a core change. There will still be a "password" column, because the list of users on the Users Page can be a mix of LDAP and local and... I guess the password field would just be hidden for non-local users, leaving some blank space in the column.

**Comment by phil-davis** [comment]
> for the CLI part, would need to detect that changing password is not supported for that user's backend and abort directly with an error message

done in PR #31

**Comment by PVince81** [comment]
to be followed up in https://github.com/owncloud/user_management/issues/42
