### ISSUE TITLE
password_policy 2.1.2

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/password_policy#291]
Reason

- [x] https://github.com/owncloud/password_policy/issues/287
- [ ] https://github.com/owncloud/password_policy/issues/286 ? 

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "2.1.2 TestPlan" @davitol https://github.com/owncloud/password_policy/issues/295
 
### Documentation

- [x] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [x] Ping @owncloud/marketing
- [x] Ping pmaier to check `info.xml` description and screenshot

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Check that no documentation issues are pending
- [x] Translations @davitol https://github.com/owncloud/password_policy/issues/295#issuecomment-604502503
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details) - https://customer.owncloud.com and https://portal.owncloud.com
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Copy email to rocket chat `#updates` channel

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/handbook/edit/master/modules/ROOT/examples/releases/server_app_release_template.md) is up to date

**Comment by micbar** [comment]
@karakayasemi @pako81 
I assigned @VicDeo for the DEV tasks,

please coordinate and share existing code / concepts

**Comment by pako81** [comment]
@VicDeo this is what I had in mind and seems to work locally. It requires changes in both core and password_policy:

- password_policy app change:

```
--- /Users/pasqualetripodi/Downloads/password_policy/lib/HooksHandler.php	2020-02-04 14:19:55.000000000 +0100
+++ /Users/pasqualetripodi/Sites/owncloud1040/apps/password_policy/lib/HooksHandler.php	2020-03-10 16:30:13.000000000 +0100
@@ -190,13 +190,13 @@
 			$date->setTime(0, 0, 0);
 			$date->add(new \DateInterval('P'.$days.'D'));
 
-			if ($params['expirationDate'] === null) {
+			if ($params['expirationDate'] === null && $params['shareType'] === '\OCP\Share::SHARE_TYPE_LINK') {
 				$params['accepted'] = false;
 				$params['message'] = (string) $this->l10n->t('An expiration date is required.');
 			}
 
 			// $date is the max expiration date
-			if ($date < $params['expirationDate']) {
+			if ($date < $params['expirationDate'] && $params['shareType'] === '\OCP\Share::SHARE_TYPE_LINK') {
 				$params['accepted'] = false;
 				$params['message'] = (string) $this->l10n->n('The expiration date cannot exceed %n day.', 'The expiration date cannot exceed %n days.', $days);
 			}
```
- core change:
```
--- /Users/pasqualetripodi/Downloads/owncloud/lib/private/Share20/Manager.php	2020-02-27 15:31:05.000000000 +0100
+++ /Users/pasqualetripodi/Sites/owncloud1040/lib/private/Share20/Manager.php	2020-03-10 16:29:43.000000000 +0100
@@ -469,6 +469,7 @@
 			'accepted' => &$accepted,
 			'message' => &$message,
 			'passwordSet' => $share->getPassword() !== null,
+			'shareType' => $share->getShareType(),
 		]);
 
 		if (!$accepted) {
```

**Comment by karakayasemi** [comment]
@pako81's solution seems okay and safe to me. As far as I see, there are no other usages of the change suggested hook in the code-base out of the password_policy app. But, the hook will be backward compatible with @pako81's solution anyway.

Also, since we have now user share expiration date, we may extend password_policy app features with user share expiration date checks without touching core in the future.

**Comment by VicDeo** [comment]
What is behavior we are fixing with the changeset above?

**Comment by pako81** [comment]
@VicDeo see https://github.com/owncloud/password_policy/issues/287

**Comment by phil-davis** [comment]
PR #293 fixes #287 and is merged. 

@HanaGemela IMO we can start the release process.

(Isssue #286 is a suggestion for improving UI workflow - IMO not to be done for this release)

**Comment by HanaGemela** [comment]
@davitol RC1 ready for testing https://github.com/owncloud/password_policy/releases/tag/v2.1.2RC1

**Comment by HanaGemela** [comment]
@davitol priority has been increased to P2

**Comment by davitol** [comment]
> @davitol RC1 ready for testing https://github.com/owncloud/password_policy/releases/tag/v2.1.2RC1

Tarball is QA-ready
