### ISSUE TITLE
[QA] Password hint will be shown, even if the required length is set to 0

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/password_policy#344]
Steps to reproduce:
1. Enable password min lowercase rule
2. Set password min lowercase rule to 0

Actual behavior:
- Hint shows At least 0 lower case letters

Expected: behavior:
- Hint should not be displayed at all 

![image](https://user-images.githubusercontent.com/26169327/124453124-54534980-dd87-11eb-9b0b-7404c1c001d4.png)

**Comment by phil-davis** [comment]
See https://github.com/owncloud/password_policy/issues/41#issuecomment-404777496

Suggestion is to prevent entering the "0" setting. If a character type requirement is "enabled" then the number must be at least 1.

**Comment by JanAckermann** [comment]
@phil-davis correct, I have set the min-value of html input to 1, but this is indeed just working if you use the controls, you could easily copy and paste a 0 char. To come all over this, we need a backend validator, and this is too much for this partcular issue.
