### ISSUE TITLE
Add test for an expired guest password

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#360]
See https://github.com/owncloud/enterprise/issues/4892

1) The admin expires the password of a guest user. (There is a test step like:
```
    When the administrator expires the password of user "Alice" using the occ command
```
and that should work with a guest user.)

2) The guest user gets an email to reset their password, and follows the link in the email.

3) The password reset screen should display and let them set a new password that meets the password policy.

Step 3 is likely to fail.

Write a test that demonstrates the problem, then it can be handed over to a dev to fix.

**Comment by SagarGi** [comment]
@phil-davis  When invoking the step 
```
    When the administrator expires the password of user "Alice" using the occ command
```
an email to reset password is not sent to the guest user. Based on that a test is added https://github.com/owncloud/password_policy/pull/373
