### ISSUE TITLE
Add options to the expire password command

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#39]
As suggested at https://github.com/owncloud/password_policy/issues/24#issuecomment-404195438

Add `--all` and `--group` options to the expire password ``occ`` command to make it more convenient to pre-expire passwords of whole groups of users or all existing users, specially when the ``password_policy`` app has been first enabled.

**Comment by PVince81** [comment]
yes, makes sense.

There are already code examples in "occ files:scan", we should use the same format for the CLI arguments and same behavior in case a group doesn't exist.

Estimate: 0.5-1md (including tests, review, docs)
