### ISSUE TITLE
Release password_policy 2.2.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/password_policy#399]
## Reason

- #394

**Comment by jnweiger** [comment]
https://github.com/owncloud/password_policy/releases/download/v2.2.0-rc.1/password_policy-2.2.0-rc.1.tar.gz

**Comment by phil-davis** [comment]
https://github.com/owncloud/password_policy/releases/tag/v2.2.0 was released 28 July 2023.

@jnweiger close this issue?

**Comment by jnweiger** [comment]
Release done as part of core 10.13.0
