### ISSUE TITLE
Notification not created when using occ user:expire-password command

### ISSUE THREAD

**Issue by PVince81** [owncloud/password_policy#47]
### Steps

1. Login as admin
1. Enable rule with 20 days until user password expires
1. Enable rule with 5 days after password expires, send notification
1. Create a user "user1" with password "test"
1. Login as "user1"
1. Run `occ user:expire-password user1 -- "-40 days"`
1. Run cron after resetting oc_jobs timetamps (the usual way to test with cron.php)
1. Refresh the page

### Expected result
Notification appears about expired password.
If a smaller value was selected, a notification about password is about to expire

### Actual result
No notification at all

### Version
Current master (2.0.0)

Looking at the code it seems that the mechanism for actual expiration is done based on the user preference "forcePasswordChange". However the notification mechanism is checking the timestamp of the last password in the password history table.

It seems that the notification code should rather look at the "forcePasswordChange" value as this is the one influenced by the last password changes. I have the feeling that there were misunderstandings during the implementation and review.

@jvillafanez please adjust the code to select based on preferences.
I seem to remember about problems when parsing the string value to int with Oracle as the preference is a CLOB and maybe using the history table is a workaround ?

In the latter case we might need to adjust the occ command to also insert a dummy password entry into the table with the same timestamp as "forcePasswordChange".

I'm not sure yet about how important this is for the release. Based on https://github.com/owncloud/password_policy/issues/24 for existing users it was said that one needs to use the occ command. So it might be best to make it work. The faster fix might be inserting a dummy password.

@butonic does that make sense ?

**Comment by PVince81** [comment]
@pmaier1 this is the reason I couldn't demo the notification. In the past I used another hack where I touched the history table but forgot at the time we talked.

@pmaier1 any thoughts on criticality considering the timeline ?

**Comment by pmaier1** [comment]
Hmm, well, this is a UX thing. Especially for existing instances that impose policies users will not receive a notification.
- won't know that password has expired until they log in again
- when not using oauth clients might throw errors about wrong password? what if we combine this with the brute-force protection app?

If these two statements are true, yes, this is at least a p2. Not sure about the effort. I actually can't defer the planned release date.

**Comment by jvillafanez** [comment]
It will depend on how we want to deal with this:
* We can send an specific notification for this case without worrying to touch the cron job. I'd expect the user to reset the password before getting more notifications from the cron job. Kind of bad as the user might receive notification from this command and the cron job.
* Same as above, but the cron job being aware of this flag. The notification would be sent right away, but the cron job will prevent sending notifications if the flag is set
* Consider this as an special case for the cron job. Basically, if the flag is set, try to send a "expired" notification. The notification would be sent by the cron job when it run.

3rd option seems to be easy enough to implement it soon.

**Comment by PVince81** [comment]
> We can send an specific notification for this case without worrying to touch the cron job. I'd expect the user to reset the password before getting more notifications from the cron job. Kind of bad as the user might receive notification from this command and the cron job.

We could later on have a special notification when triggered by admin like "Admin has expired your password" or something. This would take too much time to implement in this short time frame.

> Consider this as an special case for the cron job. Basically, if the flag is set, try to send a "expired" notification. The notification would be sent by the cron job when it run.

Reading the flag in oc_preferences additionally to the password history will likely increase complexity. It's more than a flag, it's a timestamp for potential "future expiry" or "immediate expiry". You'd need to cross-reference the tables.

After a long chat with @butonic we agreed to move forward with the solution I proposed originally:
- in the occ command, write a dummy OldPassword entry with the hash string "dummy" (don't use empty strings or nulls for now as Oracle would need special handling)
- in PasswordHistory::verify(), don't call the hasher if the $oldPassword->getPassword() hash is "dummy" to avoid confusing the hasher

@jvillafanez thoughts ?

**Comment by PVince81** [comment]
the latter solution is likely the best compromise in regards to remaining time frame

**Comment by PVince81** [comment]
talked with @jvillafanez and got agreement, he's working on it

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/password_policy/pull/51

**Comment by PVince81** [comment]
the proposed solution is a can worms, see review comments: https://github.com/owncloud/password_policy/pull/51/

I suggest we go with the simple approach: at the time where the admin runs the occ command, we trigger a notification immediately. We can't rely on the background job as it's tied to existing rules while the occ command has its own value.

@butonic @jvillafanez

**Comment by butonic** [comment]
@PVince81 agreed. should be an additional option.  We can rethink this in the next release.

**Comment by PVince81** [comment]
annnnd back to the PR, after exploring many paths, decided to continue as tweaking it should do: https://github.com/owncloud/password_policy/pull/51#issuecomment-404804951

**Comment by PVince81** [comment]
Regarding https://github.com/owncloud/password_policy/issues/47#issuecomment-404796492, it is based on an old path we explored. We're carrying on with using the bkg job mechanism to have notifications being sent (not direct notification)
