### ISSUE TITLE
Move 'different than last password' option to 'Users password policies' section

### ISSUE THREAD

**Issue by davitol** [owncloud/password_policy#49]
Different than last password option does not affect to public links, so it is located in a wrong setting in settings page

![screen shot 2018-07-13 at 09 40 12](https://user-images.githubusercontent.com/10596560/42679150-4382a962-8681-11e8-9bf9-d11f1a8ee365.png)

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/password_policy/issues/72 which has more details
