### ISSUE TITLE
Set password to expire in the future and password also happens to expire before then

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#52]
Have a user that last set their password 85 days ago, and passwords expiring after 90 days.
From occ, set the user's password to expire in 7 days time.

I expect that the user's password will expire in 5 days time, via the normal 90 day expiry setting. Then 2 days later it will expire again because of the forced expiry setting.

Is this behavior OK?

Or what should happen for passwords that come to their regular expiry time before the forced expiry time is reached?

(Just asking so I know if there is any particular behavior to require and test for that scenario)

**Comment by PVince81** [comment]
This will change / be adjusted with https://github.com/owncloud/password_policy/issues/47 and its PR.

Basically when you run occ, it will override the current regular expiration time, whatever it was. It will insert a dummy entry in the history table, as if you changed the password at the given time - days.

So the behavior should be that the password only expires once. After expiry, when you set a new password, all flags, etc are reset anyway so expiration is based again on the rule.
