### ISSUE TITLE
Notifications of delete user are kept in oc_notifications table

### ISSUE THREAD

**Issue by davitol** [owncloud/password_policy#53]
### Steps to reproduce

1. Login as admin
2. Set Password policy about expiration of password with notification
3. Create a new user and log in
4. When the notification expiration time reaches, check oc_notifications table (a row with a notification for the user appears)
5. As admin delete the user
6. Run cronjob

### Expected behavior

No log or reference to the notification of the deleted user should appear and the notifications related to the deleted user should be deleted

### Current behavior

Notifications of the deleted user are kept in the oc_notifications table and a log is shown after running the cronjob. we should probably clean that table when deleting a user.

```
Content of oc_notifications;
```

```
6|password_policy|user1|1531480850|about_to_expire|8|about_to_expire|["1531480580",172800]|["1531480580",172800]|[{"label":"Change password","link":"http:\/\/localhost:9680\/index.php\/settings\/personal?sectionid=general","type":"GET","primary":false}]||about_to_expire|http://localhost:9680/index.php/settings/personal?sectionid=general
```

```
{"reqId":"dMNHVhEqUr1apF9zGUVi","level":2,"time":"2018-07-13T12:06:05+00:00","remoteAddr":"","user":"--","app":"notifications","method":"--","url":"--","message":"notification about_to_expire#12 can't be sent to user2 via email: the user is missing"}
```

**Comment by phil-davis** [comment]
:+1: 
and if someone works on this, then you probably want to also work on the  other "left behind data" in the password history table #28

**Comment by PVince81** [comment]
Mitigated through https://github.com/owncloud/password_policy/pull/56.

Will still need proper cleanup.

**Comment by PVince81** [comment]
Mitigated through https://github.com/owncloud/password_policy/pull/56.

Will still need proper cleanup.

**Comment by PVince81** [comment]
Estimate: 0.5md

**Comment by PVince81** [comment]
put together in cleanup ticket: https://github.com/owncloud/password_policy/issues/69

**Comment by PVince81** [comment]
this is actually a core issue: https://github.com/owncloud/core/issues/32243
