### ISSUE TITLE
Password policy pattern 'different than last passwords' applies to one pwd more than the value set

### ISSUE THREAD

**Issue by davitol** [owncloud/password_policy#57]
### Steps to reproduce

1. Login as admin
2. Set Password policy '3 different than last passwords'
3. Create a new user with pwd ```aaa``` and log in
4. In settings page change password ```aaa``` to ```bbb``` (1st change)
5. In settings page change password ```bbb``` to ```ccc``` (2nd change)
6. In settings page change password ```ccc``` to ```ddd``` (3rd change)
7. In settings page change password ```ddd``` to ```aaa```

### Expected behavior

After the 3 pwd-changes, the 4th should be allowed with the password policy value set

### Current behavior

Password Policy app does not allow to change the pwd to an old one until the 5th change

**Comment by phil-davis** [comment]
@individual-it also suggested that if the admin has expired your password, then that might count as one of your "old" passwords. So in that scenario you might be able to use an old password again too quickly.
Did we test the scenario?

**Comment by PVince81** [comment]
@phil-davis I did a quick test last Friday to make sure the dummy password entries aren't counted. We should add this to the plan, yes. @davitol

**Comment by PVince81** [comment]
basically, same steps as above except that between step 5 and 6 add a `occ user:expire-password user1`
