### ISSUE TITLE
Clean up after user deletion

### ISSUE THREAD

**Issue by PVince81** [owncloud/password_policy#69]
- ~~delete notifications~~: https://github.com/owncloud/password_policy/issues/53 => https://github.com/owncloud/core/issues/32243
- [ ] delete old passwords: https://github.com/owncloud/password_policy/issues/28

Estimate: ~~0.5md for both together~~ 0.25md

**Comment by sharidas** [comment]
A clean solution for clearing notification table would be to have a method in NotificationManager which would remove the entries of user from notification table. A ticket opened at https://github.com/owncloud/core/issues/32243.
