### ISSUE TITLE
Lower case requirement + small GUI glitch

### ISSUE THREAD

**Issue by pako81** [owncloud/password_policy#7]
When having the following password requirements:

- 9 minimum characters

- 1 uppercase letters

- 1 numbers

- 1 special characters and defining them as !@#$%^&*()_-+=`~,./?;:'"[{]}|

it will accept !@#$1234A as a password. We'd ideally like for it to enforce a lower case letter as well. Would this be possible to have added?

Another thing that I noticed was when the special characters field is empty, it says to separate the characters with space or comma (which from what I can tell, isn't required).

Tested this on 10.0.4 + Password Policy app 1.1.0.

**Comment by DeepDiver1975** [comment]
> it says to separate the characters with space or comma (which from what I can tell, isn't required).

fixed already with #6
