### ISSUE TITLE
jQuery Core 1.9 Upgrade Guide

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/password_policy#71]
# jQuery Core 1.9 Upgrade Guide

Changes of Note in jQuery 1.9
See the full [upgrade guide at jquery.com](http://jquery.com/upgrade-guide/1.9/)

## Minor

`.ajax()`

- [ ] /js/ajax.js

`.attr()`

- [ ] /js/password.js

**Comment by sharidas** [comment]
Verified 
- When `Force users to change their password on first login` is opted, if user tries to enter different value in new password and confirm password in the password reset page, the save button is disabled. This is verification for `attr`.
- The ajax request to save the password policy setting is verified.

Conclusion : This functionality is not affected.

**Comment by sharidas** [comment]
Hence closing this issue.
