### ISSUE TITLE
Improve config UI

### ISSUE THREAD

**Issue by pmaier1** [owncloud/password_policy#72]
![password-policy-app](https://user-images.githubusercontent.com/21193500/43003398-b1b78a3c-8c2c-11e8-8fc5-b3319f09776a.png)

The password history part ("X different than last passwords") is
a) absolutely not understandable and
b) located wrong as this section is for both, user passwords and public link passwords.

We should find a more comprehensive wording and move that one down to "User password policies".

@PVince81

**Comment by PVince81** [comment]
Estimate: 0.25md

**Comment by PVince81** [comment]
Rename -> "Restrict to these characters"
